server:
  port: 9090

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/qs_tao?userUnicode=true&characterEncodeing=utf-8&userSSL=false&serverTimezone=GMT
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /image/**  #自定义配置
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/, file:D:/image/

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.zhou.demo.persist.po
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

alipay:
  appId: 2021000122682663
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC7evi+pNtw3mzk8ZQj6mzFO+wqafJS7fuSBfWvyAcxCHuRsQLqoYGlZuBZkT2/wyQyTQwfXFR7jIX8yCKBlryiL2dj34Bv97wXGpsYjLMReNYLqLg+TgIrIy12RDBqI3IWReiBCyw6G1aLc8xq9fn1Ke9CmLoe4am5GaQcO6OTYsOaqhdDJCOuWX8jfXs1OhYHJO1Q1+bY33eV5LOq866UjQy3SfM9u9/lVZfyoqwtWB9TIBcR0a+/8wy9maLBcJRIPTXD2NG/Rra8iyExNSTnf7wc9xZR6xKLHrjibvQ2DVZMyALj4SY3+vvuGKFaBTtE3VmFfOnEFhWtd+IgU7O1AgMBAAECggEAVRXPND5/dO8NPq5AzDgFG1JBsVIZ7vcguDnKMfe3A9LUud868p9PxnA1G5EmFBSNJeL/wG/Xy6aP3JQ7zNJLU9PtuU7i7G3jSB0EDJU2Y5SSmAH/dA9VPpydclIqItFpYqBhj8cxUEG9+lYYjOaLhW99rZzAw2ko7N+tMj8C0s00gcRS/BcMXt2UD3Fx4Ylnuhz5sXwxWx2AuLqVqvgry/yyg/FjQJktXDH0E0luPQxAv1cMzg4QdCqTp6y6Sb/r3oeTQwAFq5y1Mb+Id/TAXits+u4NyxSywhKHNwE6yL0g8F16VvUNPY9f/uhoi2iUIZmkt6wC8Gy0xtsr34Ho1QKBgQD4uamDK8MjMYmcRlLHSLHCUWRgt0ZoLQgp9doNiKoqfYfL9YU+qMVmop237Dm5hU5P3PdWMpVzy8hngKM9S7WxZRotAV4CuK8sQLIQiG15IxeSl20siRTaNbRQ7Bu6izM1fbK5ZQB/cCteBOTCKRryZMCTBoaOuZR10rowKB8U/wKBgQDA9ryPGH0rOyHId0NtmrhKunRENeHcQNSguXJwK+TgJCIo5rXzgh5Dtn09zjouYHDFF/KuvGu7csJSG+HaAQrOYZ9bQxe6Guj09TfwXILG91qYnlx4ZNO5sylO8gsmyKRRzgDxSWGZ0lUHu37g58wNUCBwcskg+4zheEs3BTZzSwKBgQC3dpN/ysbsbbzYhdLHZmqgL9M/t9B6RUUxVkRaGUWTg/anzllTh7/b3fVCVj+aBadnJ1FVxogQ2u7e0bcXHoJN8IpnSgvjLAEiPjJaGZfOc8EOgx2nbRHxhw2TZyVo6waB3U74i3Tbi4yhlDB8uz9CLmkRyg10t5S3eBGYNe//VwKBgDd+vnvo7xafyvd8VUgQVzAmr4ludaaCfqQ6sU7RUOGlgq2ArJN7uHiA40QDK3hrBAOq/4CBb/pY5sn2et3XruPr74ivowNC+fx5Cb123aWbPdLmuHFnjfy6KgcqVUqyKY/dTygVkpxKgWnX4oWMJIMvqCSu3mk97yZpEjigpyhBAoGBAN1pmc+9c7x+YfLBAmWZgC0nfihcQB48dFQdJymG+rB/uGgSj7rHsk3lHR30g7B3Pavo7qrxsJGYy68h+YJrZs2gyhfbViUGbAXRgJ4ISgCkcE38D/yIbq9O2B/SPr2qXrH9kJRQlL2L5dq9POLXyF69kuTmTRXECoexM2Mr9dHD
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAswi+PAqCRAcn8vxF9WPFAete6qXNHublCGcdfnmk/dpaKAyiCyfQPhFgwxAeegUxQLZX9qa26sITDe/5EHeFf+vhxml3eicLq8y9qOZMVnZiRB84LIAauuIJOpR8rdJHDoJPrBZ504SKq/YYWv1u4roK2kS/NJx9H55iCNa53v+fU+rJUgzgHKXjjqYhdauvgKbETVJKte6yZG2YyVv2mKoVHrVdyCEfV3TDEJXwvWbgqt17L12sWyfQ6iHR9Rh1WgJ+oLiyVYacAj0UyNCYFeyBf9DIea7uBiHtHAsXZeCstCPntRyDJ5gcEqvT+VQ74INlIFQ/e7wMDzXNvxjXoQIDAQAB
  notifyUrl: http://qstao.free.idcfengye.com/alipay/notify
  returnUrl: http://localhost:8080/#/shopIndex