server:
  port: 9090

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/qs_tao?userUnicode=true&characterEncodeing=utf-8&userSSL=false&serverTimezone=GMT
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /image/**  #自定义配置
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/, file:D:/image/

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.zhou.demo.persist.po
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl